services:
  database:
    container_name: db_mysql
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: peritech
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - deploy_network
  backend:
    container_name: app
    image: pabbraga/peritech-api:1.0
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/peritech
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    secrets:
      - db_user
      - db_password
    networks:
      - deploy_network
volumes:
  db-volume: {}
networks:
  deploy_network:
    driver: bridge